theme: jekyll-theme-minimal
title: FP Castle
logo: castle.jpg
footer-links:
  github: fpcastle
  twitter: satnam6502
plugins:
  - jekyll-seo-tag
logo: castle.jpg
twitter:
  username: satnam6502
  card: summary
tagline: Hacking Haskell in a Scottish castle
url: https://fpcastle.com
author:
  twitter: satnam6502

