theme: jekyll-theme-minimal
title: FP Castle
logo: castle.jpg
footer-links:
  github: fpcastle
  twitter: satnam6502
plugins:
  - jekyll-seo-tag
logo: castle.jpg
twitter:
  username: satnam6502
  card: summary_large_image
image: castle.jpg
tagline: Hacking Haskell in a Scottish castle
url: https://fpcastle.com

author: "Satnam Singh"

